---
version: "2"
services:
  data:
    volumes:
      # public media for nginx & django
      - ./public/static:/static
      - ./public/media:/media
      # persist data
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: redis

  elasticsearch:
    environment:
      # server memory dependent
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # - discovery.type="single-node"
    depends_on:
      - data
    volumes_from:
      - data

  logstash:
    ports:
      - "127.0.0.1:8012:12201/udp"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    ports:
      - "127.0.0.1:8056:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  django:
    depends_on:
      - data
      - redis
      - elasticsearch
      - logstash
    volumes_from:
      - data
    links:
      - redis
      - elasticsearch
      - logstash

  nginx:
    depends_on:
      - data
      - elasticsearch
      - logstash
      - django
    ports:
      - "127.0.0.1:8080:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:8012
        tag: nginx
    volumes_from:
      - data
    links:
      - django
    tty: true
